### ISSUE TITLE
theme options missing?

### ISSUE THREAD

**Issue by vjdesign** [cferdinandi/keel#60]
Hi Chris, Noticed that Theme Support menu appears in place of Theme Options menu (compared to harbor theme). Wondering, where do I set theme options?

![theme-options-missing](https://cloud.githubusercontent.com/assets/11479277/12808901/9a9a0e0a-cb6e-11e5-8e73-c0a0fdd25d7c.png)

**Comment by cferdinandi** [comment]
Hi there - not sure which version of Keel you're running, but on the latest, `keel_developer_options()` only includes an option for Theme Support, not a theme options page. 

Depending your project, you may not need any theme options at all, or you may need a ton. As a result, I omitted theme options from Keel altogether. If you'd like to add them, I'd recommend https://github.com/cferdinandi/wp-theme-options.

See http://keel.gomakethings.com/documentation/wordpress-specific-features/#theme-support for more info.
