### ISSUE TITLE
Where is jQuery being deregistered?

### ISSUE THREAD

**Issue by am3000** [cferdinandi/keel#70]
I´m trying to find the code where the default jQuery script is being deregistered ... cannot find anything in functions.php

Thanks

**Comment by cferdinandi** [comment]
It's not being deregistered, but I believe because no script has called it as a dependency, it never loads. If you're trying to use jQuery in a theme, make sure that whatever script you request lists it as a dependency.

**Comment by am3000** [comment]
Thanks alot for your quick response!
