### ISSUE TITLE
get_template_directory_uri() in  keel_load_inline_header()

### ISSUE THREAD

**Issue by am3000** [cferdinandi/keel#75]
Hey, shouldn´t get_template_directory_uri() in the function  keel_load_inline_header() (functions.php) be replaced with get_template_directory()?
Otherwise file_get_contents is making a http request ... i guess, not sure ;)

`
<?php echo file_get_contents( get_template_directory_uri() . '/dist/js/detects.min.' . $keel_theme->get( 'Version' ) . '.js' ); ?>
			</script>
`

**Comment by cferdinandi** [comment]
I'm not 100% sure about the HTTP request piece, but passing in the path works, too, so I switched them all over with https://github.com/cferdinandi/keel/pull/76. Thanks!
